In [10]:
from turtle import pos
import torch
from torch import nn
import pytorch_lightning as pl
import math
import src.models as models

In [24]:
tensor=torch.tensor([[3,3,3,3, 57, 2538, 3853, 42, 462]])
mask = tensor.ne(3)
torch.cumsum(mask, dim=1)

tensor([[0, 0, 0, 0, 1, 2, 3, 4, 5]])

In [2]:
encoder_model = models.EncoderModel.load_from_checkpoint("/home/is/armin-sa/Projects/lm/lightning_logs/version_9/checkpoints/epoch=19-step=3680.ckpt",vocab_size=8000)


In [45]:
with torch.no_grad():
    tmp = encoder_model(torch.tensor([[3,2,4,3]]))
print(tmp.argmax())
# print(tmp.softmax(-1)[0][0])

tensor(11)


In [6]:
with torch.no_grad():
    tmp = encoder_model(torch.tensor([[1, 140, 109, 96, 2030, 57, 2538, 3853, 42, 462]])).softmax(-1) #1 140 109 96 2030 57 2538 3853 42 462 3522 2
print(tmp.argmax(-1))
print(tmp)

tensor([42])
tensor([[2.5176e-18, 5.0208e-16, 5.4215e-06,  ..., 3.4650e-15, 1.7169e-15,
         1.8673e-10]])
