In [1]:
from turtle import pos
import torch
from torch import nn
import pytorch_lightning as pl
import math
import src.models as models

/home/is/armin-sa/miniconda3/envs/pytorch/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tensor=torch.tensor([[3,3,3,3, 57, 2538, 3853, 42, 462]])
mask = tensor.ne(3)
torch.cumsum(mask, dim=1)

tensor([[0, 0, 0, 0, 1, 2, 3, 4, 5]])

In [3]:
encoder_model = models.EncoderModel.load_from_checkpoint("/home/is/armin-sa/Projects/lm/lightning_logs/version_3/checkpoints/epoch=1-step=18005.ckpt",vocab_size=16000)


In [4]:
with torch.no_grad():
    tmp = encoder_model(torch.tensor([[3,2,4,3]]))
print(tmp.argmax())
# print(tmp.softmax(-1)[0][0])

tensor(4)


In [22]:
with torch.no_grad():
    # 1 7421 4 7 178 8 298 4 14 115 8457 1029 1060 27 82 9632 13 2648 306 56 2
    tmp = encoder_model(torch.tensor([[1, 7421, 4, 7]])).softmax(-1)
print(tmp.argmax(-1))
print(tmp)

tensor([4])
tensor([[3.8410e-06, 1.3128e-07, 1.5367e-03,  ..., 3.3972e-07, 4.1753e-07,
         8.8305e-08]])
