In [10]:
import torch, sys, random
from torch import nn
import pytorch_lightning as pl
from pathlib import Path
import numpy as np
from copy import deepcopy
import pytorch_lightning as pl
from torch.utils.data import random_split, DataLoader
from typing import Optional
import src.datasets as datasets
import src.models as models

In [11]:
main_dm = datasets.MainDataModule(datasets.TrainDataSet("data/ru_small.bin", "data/sample_locs.npy", 8))
test_ds = datasets.TestDataSet()
test_dl = DataLoader(test_ds, batch_size=8)

In [17]:
main_dm.setup()
ld = main_dm.train_dataloader()
it = iter(ld)


In [23]:
next(it)

tensor([[   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            1,  125,    4, 1978,   63,    7, 4083,   35,  161,   56,    8,   35,
         4292,   56, 1488, 4146,    4,    2],
        [   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3, 

In [ ]:
# baseline_model = models.BaselineModel()

In [ ]:
# trainer = pl.Trainer(
#     limit_train_batches=10000, max_epochs=2, accelerator="gpu", devices=1
# )
# trainer.fit(model=baseline_model, datamodule=main_dm)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name      | Type       | Params
-----------------------------------------
0 | embedding | Embedding  | 16.4 M
1 | encoder   | Sequential | 2.1 M 
-----------------------------------------
34.9 M    Trainable params
0         Non-trainable params
34.9 M    Total params
139.471   Total estimated model params size (MB)


Epoch 0:   3%|▎         | 45/1452 [00:05<02:46,  8.43it/s, loss=10.2, v_num=3]

/home/is/armin-sa/miniconda3/envs/pytorch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:653: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")


In [ ]:
with torch.no_grad():
    tmp = baseline_model(torch.full((2,), 3))
tmp.argmax()


tensor(3)

In [24]:
a = torch.tensor([[   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            1,  125,    4, 1978,   63,    7, 4083,   35,  161,   56,    8,   35,
         4292,   56, 1488, 4146,    4,    2],
        [   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            1, 2165,  273, 1840,  172,   54,  981, 1586,  197,   66,  915,    6,
         5842,   13, 7175,    7,    5,    2],
        [   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    1,  360,  232,  141, 4252, 4998,    5, 1606,   10,
         4738,   10,   73, 1136, 3560,    7, 2757,    7,    4, 1127,    7, 3425,
           53, 5635,  251, 3280,  136, 3302,    4,   19,   25,  587,  155, 1095,
         4541, 1009,    4,   33, 5316,   28,    5,  118, 4374,    6,  362,  370,
          130,  135, 1106,   41,  641, 2514, 5316,  160, 7914,   13,   82, 2534,
         5865,  671,   50, 5277,    5,    2],
        [   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    1,   27, 2023,  155,   12,   53, 7277,    7, 1931, 2431,
          565,   18,  884, 4126,   17,  120,  499,    4,   30, 1287,  114, 3673,
         6126, 3325,   58,   71, 1117, 4954,   22,   71,  378,   14, 2475, 1026,
           37,    4,   41,   30, 6765,  114,   31,   71,  516,  884,  441,    5,
           20,  248,    9,  253,   26,    2]], dtype=torch.int32)

In [27]:
a=a[2:,:]

In [28]:
a

tensor([[   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    1,  360,  232,  141, 4252, 4998,    5, 1606,   10,
         4738,   10,   73, 1136, 3560,    7, 2757,    7,    4, 1127,    7, 3425,
           53, 5635,  251, 3280,  136, 3302,    4,   19,   25,  587,  155, 1095,
         4541, 1009,    4,   33, 5316,   28,    5,  118, 4374,    6,  362,  370,
          130,  135, 1106,   41,  641, 2514, 5316,  160, 7914,   13,   82, 2534,
         5865,  671,   50, 5277,    5,    2],
        [   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
            3,    3,    3,    3,    3,    3,    3,    3,    3, 

In [31]:
b = a.unfold(1, min(1024, int(a.shape[1] / 2)), 1)
b

tensor([[[   3,    3,    3,  ...,    3,    3,    3],
         [   3,    3,    3,  ...,    3,    3,    1],
         [   3,    3,    3,  ...,    3,    1,  360],
         ...,
         [   3,    3,    1,  ...,  671,   50, 5277],
         [   3,    1,  360,  ...,   50, 5277,    5],
         [   1,  360,  232,  ..., 5277,    5,    2]],

        [[   3,    3,    3,  ...,    3,    3,    3],
         [   3,    3,    3,  ...,    3,    3,    3],
         [   3,    3,    3,  ...,    3,    3,    3],
         ...,
         [   3,    3,    3,  ...,  248,    9,  253],
         [   3,    3,    3,  ...,    9,  253,   26],
         [   3,    3,    3,  ...,  253,   26,    2]]], dtype=torch.int32)

In [34]:
b[0][0]

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=torch.int32)

In [36]:
b[(b != 3).logical_and(b != 1).any(axis=2)]

tensor([[  3,   3,   3,  ...,   3,   1, 360],
        [  3,   3,   3,  ...,   1, 360, 232],
        [  3,   3,   3,  ..., 360, 232, 141],
        ...,
        [  3,   3,   3,  ..., 248,   9, 253],
        [  3,   3,   3,  ...,   9, 253,  26],
        [  3,   3,   3,  ..., 253,  26,   2]], dtype=torch.int32)